import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import Navbar from './Components/Navbar/Navbar'
import Providers from './Provider/Provider'


const inter = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'dinemarket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
            <Navbar />
            {children}
        </Providers>
      </body>
    </html>
  )
}
